# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: SC HMIS
    url: https://sp5.servicept.com/sc211/com.bowmansystems.sp5.core.ServicePoint/index.html
  - name: SC HMIS Training
    url: https://sp5.servicept.com/sc211/com.bowmansystems.sp5.core.ServicePoint/index.html
  - name: ECHO Site
    url: https://echousing.org
  - name: Tech Support Help Desk
    url: https://support.echousing.org
  - name: Maintenance Help Desk
    url: https://maint.echousing.org
  - name: ECHO MB Office
    url: 206.195.76.113
  - name: Nardmoor
    url: 65.190.107.46

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.echousing.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ECHO Status Monitor
  introTitle: "Monitoring Eastern Carolina Housing Organization Web Services"
  introMessage: Using technology to benefit our community
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
