# Change these first
owner: echousing # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: SC HMIS
    url: https://sp5.servicept.com/sc211/com.bowmansystems.sp5.core.ServicePoint/index.html
    expectedStatusCodes:
      - 200
  - name: SC HMIS Training
    url: https://sp5.servicept.com/sc211/com.bowmansystems.sp5.core.ServicePoint/index.html
    expectedStatusCodes:
      - 200
  - name: ECHO Site and Main VM
    url: https://echousing.org


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.echousing.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://echousing.org/wp-content/uploads/echo-new-300-1.png
  name: ECHO Status Monitor
  introTitle: "Monitoring Eastern Carolina Housing Organization Web Services"
  introMessage: Using technology to benefit our community
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
